### PR TITLE
Terraform 12

### PR DESCRIPTION
**Pull request by jseiser**
This should work for Terraform 12.

You would/will want to cut a version 11 compatible branch.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @jseiser !

@phuonghuynh could you help review, tag a release for terraform v11 (make a separate branch for it), and merge this PR to master if okay? Thanks!

**Review by CAMOBAP — APPROVED** [review]
Looks right! But it's really difficult to review this code (to not miss an arror)

@ronaldtse should we add GHA workflow to run `terraform validate`?

**Comment by phuonghuynh** [comment]
Yes

**Review by phuonghuynh — APPROVED** [review]
LGTM

**Comment by ronaldtse** [comment]
> @ronaldtse should we add GHA workflow to run terraform validate?

Yes please, thanks @CAMOBAP795 !

**Comment by jseiser** [comment]
@ronaldtse 
@phuonghuynh 

You guys may want to update the README, and the terraform registry entry, to specify which versions track 11 and 12.

**Pull request merged**
